# Generated by Django 3.2.23 on 2024-01-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitInfo',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('p_color', models.IntegerField()),
            ],
        ),
    ]
