# Generated by Django 3.2.23 on 2024-01-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitinfo',
            name='data',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
