# Generated by Django 3.2.23 on 2024-01-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0003_rename_data_outfitinfo_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitinfo',
            name='image_data',
            field=models.TextField(null=True),
        ),
    ]
